### PR TITLE
Feature/put delete

### PR DESCRIPTION
**Pull request by Atria64**

### CODE REVIEW

**Review by sakupi01 — APPROVED** [review]
LGTM

**Comment by ajfAfg** [comment]
Happy Coder

**Comment by sakupi01** [comment]
https://chromewebstore.google.com/detail/copy-lgtm/lakeepohjegichaoakaaambeaipdcdmf

**Review by ajfAfg — COMMENTED** [review]
Nice!

**Review by laft2 — APPROVED** [review]
LGTM

**Comment by sakupi01** [comment]
Looking perfect to me!!

**Pull request merged**
